import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";
import { Toaster } from "sonner";
import { DropdownNav } from "./_Provider/DropdownNav";
import MainView from "./_ui/MainView";
import { Analytics } from "@vercel/analytics/next";

const JosefinSans = Josefin_Sans({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "Helpersaurus - %s",
    default: "Helpersaurus - Free Tools For Development",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${JosefinSans.className} antialiased`}>
        <DropdownNav>
          <MainView>
            <Analytics />
            <Navigation />
            <Toaster position="top-center" richColors />
            {children}
          </MainView>
        </DropdownNav>
      </body>
    </html>
  );
}
